`import Ember from 'ember'`
`import DS from 'ember-data'`

Directive = DS.Model.extend
  title:    DS.attr()
  body:     DS.attr()
  date:     DS.attr('date')
  category: DS.attr()
  body_html: (->
    converter = new Showdown.converter()
    new Ember.Handlebars.SafeString(converter.makeHtml(@get('body')))
  ).property('body')
  body_preview: (->
    converter = new Showdown.converter()
    html = new Ember.Handlebars.SafeString(converter.makeHtml(@get('body')))
    S(html).stripTags().left(100)
  ).property('body')

Directive.reopenClass
  FIXTURES: [
    { id:  1, title: 'No more TicTacToe',                     date: moment("2014-12-10T22:40:06Z").toDate(), category: 'chemtrails',   body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  2, title: 'Quartely report: Q4/2014',              date: moment("2014-12-07T00:15:42Z").toDate(), category: 'seignorage',   body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  3, title: 'New objectives for January 2015',       date: moment("2014-12-05T12:29:18Z").toDate(), category: 'haarp',        body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  4, title: 'New chemical: cobalt',                  date: moment("2014-12-03T14:23:08Z").toDate(), category: 'chemtrails',   body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  5, title: 'Errata corrige',                        date: moment("2014-12-02T10:58:05Z").toDate(), category: 'vaccines',     body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  6, title: 'New sterilization campaing',            date: moment("2014-11-30T14:55:08Z").toDate(), category: 'vaccines',     body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  7, title: 'Status update',                         date: moment("2014-11-29T01:15:58Z").toDate(), category: 'mind-control', body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  8, title: 'New recruitment campaign',              date: moment("2014-11-27T13:40:34Z").toDate(), category: 'politics',     body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id:  9, title: 'Spraying campaing in nort Italy',       date: moment("2014-11-25T21:31:14Z").toDate(), category: 'chemtrails',   body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id: 10, title: 'New objectives for December',           date: moment("2014-11-25T10:46:45Z").toDate(), category: 'haarp',        body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id: 11, title: 'Shut down all floodings in nort Italy', date: moment("2014-11-25T06:00:22Z").toDate(), category: 'haarp',        body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id: 12, title: 'Please stop wasting good money',        date: moment("2014-11-23T12:40:32Z").toDate(), category: 'seignorage',   body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
    { id: 13, title: 'WARNING: Traitor alert',                date: moment("2014-11-22T00:03:10Z").toDate(), category: 'politics',     body: 'Lorem markdownum **aqua**, ille lacus ventos, cursus nido, dum et litus\nexitioque parabat, et? Opesque errare foedera miratur spectat maior. Illius et\nCyprio Boebes imperet recentia magis petere, ait non arma nec sui novitate.\n\nFacit de quam Thracia **figura** quodsi, rex et malo motis est sequentes tangit\nmedium. Nostro tum neque, cui non prodigiosa Latous. Caput iam. *Fixus* facit\nseptemplicis radice, *corpus*, et et si est.\n\n## Tempora iudicis lacrimis temptant\n\nOriens melle turbata discite praesentia abiit iuvenalia videri: ullo pete\n[auctor](http://imgur.com/) non moenia hora quoque ulterius teneri! Irata dei\npetentes inmensae peregit *enituntur saucius* volucres frustra pondus cura\naccipit.\n\n- Cynthia Meropis que quod nulla sepulcrum natura\n- Sicut Iove pede sua quoniam duro\n- Partes procul tellure cava\n- Si humilem media\n'}
  ]

`export default Directive`
